name: Blablasah
favicon: null
layout_spectrum: 0.8895
typography_spectrum: 0.54941
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1d1b'
    - '#bc973f'
    - '#ffffff'
    - '#797979'
    - '#e0cea5'
  brandStrength: 1
  lightness: 0.7044689415488392
  saturation: 0
  rhythmicContrast: 0.2764744497835636
purpose: []
