name: Blablasah
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9331327311228961
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6875
  lightness: 0.7044689415488392
  saturation: 0.8893857072107494
  rhythmicContrast: 0.2764744497835636
purpose: []
